src/main/java/br/com/futebolmobile/model/Campeonato.java
package br.com.futebolmobile.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

@Entity
public class Campeonato implements Serializable{

	private static final long serialVersionUID = 1L;

	@Id
    @GeneratedValue
    private Integer id;
	
	private String nome;
	
	private String alias;

	@ManyToMany(fetch=FetchType.EAGER)
	@Fetch(FetchMode.SUBSELECT)
	private List<Jogo> jogos = new ArrayList<Jogo>();
	
	@ManyToMany(fetch=FetchType.EAGER)
	@Fetch(FetchMode.SUBSELECT)
	private List<Classificacao> classificacao = new ArrayList<Classificacao>();
	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getAlias() {
		return alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	public List<Jogo> getJogos() {
		return jogos;
	}

	public void setJogos(List<Jogo> jogos) {
		this.jogos = jogos;
	}
	
	public void adicionaJogo(Jogo jogo) {
		this.jogos.add(jogo);
	}
	
	public void removeJogo(Jogo jogo) {
		this.jogos.remove(jogo);
	}

	public List<Classificacao> getClassificacao() {
		return classificacao;
	}

	public void setClassificacao(List<Classificacao> classificacao) {
		this.classificacao = classificacao;
	}
	
}

src/main/java/br/com/futebolmobile/model/Classificacao.java
package br.com.futebolmobile.model;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

@Entity
public class Classificacao implements Serializable{

	private static final long serialVersionUID = 1L;

	@Id
    @GeneratedValue
    private Integer id;
	
	private Integer posicao;
	
	private Integer jogos;
	
	private Integer vitorias;
	
	private Integer saldoGols;
	
	private Integer pontos;
	
	private String grupo;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getPosicao() {
		return posicao;
	}

	public void setPosicao(Integer posicao) {
		this.posicao = posicao;
	}

	public Integer getJogos() {
		return jogos;
	}

	public void setJogos(Integer jogos) {
		this.jogos = jogos;
	}

	public Integer getVitorias() {
		return vitorias;
	}

	public void setVitorias(Integer vitorias) {
		this.vitorias = vitorias;
	}

	public Integer getSaldoGols() {
		return saldoGols;
	}

	public void setSaldoGols(Integer saldoGols) {
		this.saldoGols = saldoGols;
	}

	public Integer getPontos() {
		return pontos;
	}

	public void setPontos(Integer pontos) {
		this.pontos = pontos;
	}

	public String getGrupo() {
		return grupo;
	}

	public void setGrupo(String grupo) {
		this.grupo = grupo;
	}
	
}

src/main/java/br/com/futebolmobile/model/EntidadeDominio.java
package br.com.futebolmobile.model;

public class EntidadeDominio {

}

src/main/java/br/com/futebolmobile/model/Time.java
package br.com.futebolmobile.model;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

@Entity
public class Time implements Serializable{

	private static final long serialVersionUID = 1L;

	@Id
    @GeneratedValue
    private Integer id;
	
	private String nome;
	
	private String alias;
	
	private Integer muralAtivado;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getAlias() {
		return alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}
	
	public Integer getMuralAtivado() {
		return muralAtivado;
	}

	public void setMuralAtivado(Integer muralAtivado) {
		this.muralAtivado = muralAtivado;
	}

	public String getMuralAtivadoString() {
		String muralAtivadoString = "";
		
		if (muralAtivado == null) {
			muralAtivadoString = "";
		}
		else if(muralAtivado == 0){
			muralAtivadoString = "Inativado";
		}
		else if(muralAtivado == 1){
			muralAtivadoString = "Ativado";
		}
		return muralAtivadoString;
	}
	
}

src/main/java/br/com/futebolmobile/model/Usuario.java
package br.com.futebolmobile.model;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;

@Entity
public class Usuario implements Serializable{

	private static final long serialVersionUID = 1L;

	@Id
    @GeneratedValue
    private Integer id;
	
	private String nome;
	
	private String local;
	
	private String email;
	
	@ManyToOne
	private Time time;
	
	private String idFacebook;
	
	private Integer status;
	
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getLocal() {
		return local;
	}

	public void setLocal(String local) {
		this.local = local;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Time getTime() {
		return time;
	}

	public void setTime(Time time) {
		this.time = time;
	}

	public String getIdFacebook() {
		return idFacebook;
	}

	public void setIdFacebook(String idFacebook) {
		this.idFacebook = idFacebook;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
	
	public String getStatusString() {
		String statusString = "";
		
		if (status == null) {
			statusString = "";
		}
		else if(status == 0){
			statusString = "Bloqueado";
		}
		else if(status == 1){
			statusString = "Desbloqueado";
		}
		return statusString;
	}

	
}

src/main/java/br/com/futebolmobile/model/UsuarioLogin.java
package br.com.futebolmobile.model;

import java.io.Serializable;
import java.util.List;

import javax.inject.Inject;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import org.apache.commons.codec.binary.Base64;

import br.com.futebolmobile.facade.UsuarioLoginFacade;

@Entity
public class UsuarioLogin implements Serializable{
	
	private static final long serialVersionUID = 1L;
	
	@Inject
	private UsuarioLoginFacade usuarioLoginFacade;
	
	@Id
    @GeneratedValue
    private Integer id;
    private String email;
    private String senha;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }
	
    public List<UsuarioLogin>usuarios(){
    	return usuarioLoginFacade.selectAll();
    }
    
    public static String criptografiaBase64Encoder(String senha) {
        return new Base64().encodeToString(senha.getBytes());
    }
    public static String descriptografiaBase64Decoder(String senha) {
        return new String(new Base64().decode(senha));
    }
    
    
}

src/main/java/br/com/futebolmobile/mb/TemaMB.java
package br.com.futebolmobile.mb;

import java.io.Serializable;

import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

@Named
@SessionScoped
public class TemaMB implements Serializable{

	private static final long serialVersionUID = 1L;
	
	private String tema = "bluesky";

	public String getTema() {
		return tema;
	}

	public void setTema(String tema) {
		this.tema = tema;
	}
	
	public String[] getTemas() {
	    return new String[] { "afterdark", "afternoon", "afterwork", "aristo",
	            "black-tie", "blitzer", "bluesky", "bootstrap", "casablanca",
	            "cupertino", "cruze", "dark-hive", "delta", "dot-luv",
	            "eggplant", "excite-bike", "flick", "glass-x", "home",
	            "hot-sneaks", "humanity", "le-frog", "midnight", "mint-choc",
	            "overcast", "pepper-grinder", "redmond", "rocket", "sam",
	            "smoothness", "south-street", "start", "sunny", "swanky-purse",
	            "trontastic", "ui-darkness", "ui-lightness", "vader" };
	}
}

src/main/webapp/_template.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:mj="http://mojarra.dev.java.net/mojarra_ext"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:fn="http://java.sun.com/jsp/jstl/functions">
	
	<h:head/>
    
    <h:body>
        <div id="cabecalho">
            <h1><ui:insert name="titulo"></ui:insert></h1>
        </div>
        
		<h:panelGrid columns="2">
			<h:form rendered="#{usuarioLogado != null}" >
    			<p:themeSwitcher id="escolherTema" style="width:165px" value="#{temaMB.tema}">
        			<f:selectItem itemLabel="Escolher tema" itemValue="" />
        			<f:selectItems value="#{temaMB.temas}" var="tema" itemLabel="#{tema}" itemValue="#{tema}" />
    				<f:ajax />
    			</p:themeSwitcher>
			</h:form>
		</h:panelGrid>
		
        <p:growl id="growl" showDetail="true" autoUpdate="true" sticky="true"/>
        
        <h:form id="formMenu" rendered="#{usuarioLogado != null}">     
	        <p:menubar>
	   			<p:submenu label="Cadastros" icon="ui-icon-document">
	            	<p:menuitem value="Times" action="time?faces-redirect=true"  icon="fa fa-fw fa-edit" />
	                <p:separator />
	            	<p:menuitem value="Campeonatos" action="campeonato?faces-redirect=true"  icon="fa fa-fw fa-edit"/>
	            	<p:separator />
	            	<p:menuitem value="Jogos" action="jogo?faces-redirect=true"  icon="fa fa-fw fa-edit"/>
	            	<p:separator />
	            	<p:menuitem value="Usuários" action="usuario?faces-redirect=true"  icon="fa fa-fw fa-edit"/>	            	
			    	<p:separator />
	            	<p:menuitem value="Classificação" action="classificacao?faces-redirect=true"  icon="fa fa-fw fa-edit"/>	            	
			    </p:submenu>
    			
    			<p:submenu label="Outros">
     				<p:menuitem value="Usuários de Sistema" action="usuarioLogin?faces-redirect=true"  icon="fa fa-fw fa-edit"/>	
        			<p:menuitem value="Logout" action="#{loginMB.deslogar}" icon="fa fa-fw fa-sign-out"/>		
    			</p:submenu>
			</p:menubar>
        </h:form>

        <div id="conteudo">
            <ui:insert name="conteudo">
            </ui:insert>
        </div>      
    </h:body>
</html>

src/main/webapp/campeonato.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:fn="http://java.sun.com/jsp/jstl/functions">

	<ui:composition template="_template.xhtml">

        <ui:define name="titulo">
                <p:outputPanel>Campeonatos</p:outputPanel>
        </ui:define>

        <ui:define name="conteudo">
         
        
        <h:messages globalOnly="true" />
            
        <h:form id="campeonato">
                <p:fieldset legend="Dados do Campeonato">
                    <h:panelGrid columns="2">
								
					<p:outputLabel value="Nome:" for="nome" />
					<p:inputText id="nome" value="#{campeonatoMB.campeonato.nome}"
						required="true">
						<f:validateLength minimum="2" />
					</p:inputText>

					<p:outputLabel value="Alias:" for="alias"/>
					<p:inputText id="alias" value="#{campeonatoMB.campeonato.alias}"
						required="true">
						<f:validateLength minimum="1" />
					</p:inputText>
							
				  </h:panelGrid>
				<p:commandButton value="Gravar" action="#{campeonatoMB.gravar}" process="@form" update="@form formTabelaCampeonatos" ajax="false" />
			</p:fieldset>    
		</h:form>
		
		<h:form id="formTabelaCampeonatos">
		  <p:dataTable var="campeonato" value="#{campeonatoMB.campeonatos}" rows="10" paginator="true">
                    <f:facet name="header">
                    	Lista de Campeonatos Cadastrados
                    </f:facet>
                    <p:column headerText="Código" sortBy="#{campeonato.id}"
                           filterBy="#{campeonato.id}">                           
                           <h:outputText value="#{campeonato.id}" />
                    </p:column>
                    <p:column headerText="Nome" sortBy="#{campeonato.nome}"
                           filterBy="#{campeonato.nome}">                           
                           <h:outputText value="#{campeonato.nome}" />
                    </p:column>
  
  					<p:column headerText="Alias" sortBy="#{campeonato.alias}"
                           filterBy="#{campeonato.alias}">
                           <h:outputText value="#{campeonato.alias}" />
                    </p:column>
  
					<!-- Alterar  -->
                    <p:column headerText="Alterar" >
                     	<p:commandButton icon="fa fa-fw fa-edit" value="Alterar" update=":campeonato">
            				<f:setPropertyActionListener value="#{campeonato}" target="#{campeonatoMB.campeonato}" />
        				</p:commandButton>
                    </p:column>
                   
                    <!-- Remover -->
                     <p:column headerText="Remover" >
                           <p:commandButton icon="fa fa-fw fa-remove" value="Remover" action="#{campeonatoMB.delete(campeonato)}" update="@form" />
                    </p:column>
             </p:dataTable>
		</h:form>
	
	
	</ui:define>
</ui:composition>

</html>

src/main/webapp/classificacao.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions">

<ui:composition template="_template.xhtml">

	<ui:define name="titulo">
		<p:outputPanel>Classificação #{campeonato.nome}</p:outputPanel>
	</ui:define>

	<ui:define name="conteudo">


		<h:messages globalOnly="true" />

		<h:form id="usuario">
			<p:fieldset legend="Classificação">
				<h:panelGrid columns="2">

					<p:outputLabel value="Nome do Campeonato:" for="nome" />
					<p:inputText id="nome" value="#{campeonatoMB.campeonato.nome}" required="true"/>

				
				</h:panelGrid>

				
				<p:commandButton value="Gravar" action="#{usuarioMB.gravar}"
					process="@form" update="@form formTabelaUsuarios" ajax="false" />
			</p:fieldset>
		</h:form>

		<h:form id="formTabelaUsuarios">
			<p:dataTable var="usuario" value="#{usuarioMB.usuarios}" rows="10"
				paginator="true">
				
				<f:facet name="header">
                    	Lista de Usuários Cadastrados
                </f:facet>
				
				<p:column headerText="Código" sortBy="#{usuario.id}"
					filterBy="#{usuario.id}">
					<h:outputText value="#{usuario.id}" />
				</p:column>
				
				<p:column headerText="Nome" sortBy="#{usuario.nome}"
					filterBy="#{usuario.nome}">
					<h:outputText value="#{usuario.nome}"/>
				</p:column>

				<p:column headerText="Time" sortBy="#{usuario.time}"
					filterBy="#{usuario.time}">
					<h:outputText value="#{usuario.time}"/>
				</p:column>

				<p:column headerText="Local" sortBy="#{usuario.local}"
					filterBy="#{usuario.local}">
					<h:outputText value="#{usuario.local}"/>
				</p:column>
				
				<p:column headerText="Email" sortBy="#{usuario.email}"
					filterBy="#{usuario.email}">
					<h:outputText value="#{usuario.email}"/>
				</p:column>
				
				<p:column headerText="Status" sortBy="#{usuario.status}"
					filterBy="#{usuario.status}">
					<h:outputText value="#{usuario.statusString}"/>
				</p:column>
				
				<p:column headerText="ID Facebook" sortBy="#{usuario.idFacebook}"
					filterBy="#{usuario.idFacebook}">
					<h:outputText value="#{usuario.idFacebook}"/>
				</p:column>
				
				
				<!-- Alterar  -->
				<p:column headerText="Alterar">
					<p:commandButton icon="fa fa-fw fa-edit" value="Alterar"
						update=":usuario">
						<f:setPropertyActionListener value="#{usuario}"
							target="#{usuarioMB.usuario}" />
					</p:commandButton>
				</p:column>

				<!-- Remover -->
				<p:column headerText="Remover">
					<p:commandButton icon="fa fa-fw fa-remove" value="Remover"
						action="#{usuarioMB.delete(usuario)}" update="@form" />
				</p:column>
			</p:dataTable>
		</h:form>


	</ui:define>
</ui:composition>

</html>

src/main/webapp/inicio.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions">

<ui:composition template="_template.xhtml">

	<ui:define name="titulo">
		<p:outputPanel>Início</p:outputPanel>
	</ui:define>

	<ui:define name="conteudo">


		<h:messages globalOnly="true" />

		<h:form id="usuario">
			<p:fieldset legend="Dados do Usuário">
				<h:panelGrid columns="2">

					<p:outputLabel value="Nome:" for="nome" />
					<p:inputText id="nome" value="#{usuarioMB.usuario.nome}" required="true"/>

					<p:outputLabel value="Local:" for="local" />
					<p:inputText id="local" value="#{usuarioMB.usuario.local}"
						required="true">
						<f:validateLength minimum="1" />
					</p:inputText>

					<p:outputLabel value="Email:" for="email" />
					<p:inputText id="email" value="#{usuarioMB.usuario.email}"
						required="true">
						<f:validateLength minimum="1" />
					</p:inputText>

					<p:outputLabel value="Status:" for="status" />
					<p:selectOneMenu id="status" value="#{usuarioMB.usuario.status}">
						<f:selectItem itemLabel="Desbloqueado" itemValue="1" />
						<f:selectItem itemLabel="Bloqueado" itemValue="0" />
					</p:selectOneMenu>

					<p:outputLabel value="ID Facebook:" for="idFacebook" />
					<p:inputText id="idFacebook" value="#{usuarioMB.usuario.idFacebook}"
						required="true">
						<f:validateLength minimum="1" />
					</p:inputText>

					<p:outputLabel value="Selecione Time:" for="time" />
					<p:selectOneMenu value="#{jogoMB.timeId}" id="time">
						<f:selectItems value="#{jogoMB.times}" var="time"
							itemLabel="#{time.nome}" itemValue="#{time.id}" />
					</p:selectOneMenu>

				</h:panelGrid>

				
				<p:commandButton value="Gravar" action="#{usuarioMB.gravar}"
					process="@form" update="@form formTabelaUsuarios" ajax="false" />
			</p:fieldset>
		</h:form>

		<h:form id="formTabelaUsuarios">
			<p:dataTable var="usuario" value="#{usuarioMB.usuarios}" rows="10"
				paginator="true">
				
				<f:facet name="header">
                    	Lista de Usuários Cadastrados
                </f:facet>
				
				<p:column headerText="Código" sortBy="#{usuario.id}"
					filterBy="#{usuario.id}">
					<h:outputText value="#{usuario.id}" />
				</p:column>
				
				<p:column headerText="Nome" sortBy="#{usuario.nome}"
					filterBy="#{usuario.nome}">
					<h:outputText value="#{usuario.nome}"/>
				</p:column>

				<p:column headerText="Time" sortBy="#{usuario.time}"
					filterBy="#{usuario.time}">
					<h:outputText value="#{usuario.time.nome}"/>
				</p:column>

				<p:column headerText="Local" sortBy="#{usuario.local}"
					filterBy="#{usuario.local}">
					<h:outputText value="#{usuario.local}"/>
				</p:column>
				
				<p:column headerText="Email" sortBy="#{usuario.email}"
					filterBy="#{usuario.email}">
					<h:outputText value="#{usuario.email}"/>
				</p:column>
				
				<p:column headerText="Status" sortBy="#{usuario.status}"
					filterBy="#{usuario.status}">
					<h:outputText value="#{usuario.statusString}"/>
				</p:column>
				
				<p:column headerText="ID Facebook" sortBy="#{usuario.idFacebook}"
					filterBy="#{usuario.idFacebook}">
					<h:outputText value="#{usuario.idFacebook}"/>
				</p:column>
				
				
				<!-- Alterar  -->
				<p:column headerText="Alterar">
					<p:commandButton icon="fa fa-fw fa-edit" value="Alterar"
						update=":usuario">
						<f:setPropertyActionListener value="#{usuario}"
							target="#{usuarioMB.usuario}" />
					</p:commandButton>
				</p:column>

				<!-- Remover -->
				<p:column headerText="Remover">
					<p:commandButton icon="fa fa-fw fa-remove" value="Remover"
						action="#{usuarioMB.delete(usuario)}" update="@form" />
				</p:column>
			</p:dataTable>
		</h:form>


	</ui:define>
</ui:composition>

</html>

src/main/webapp/login.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

	 
    <ui:composition template="_template.xhtml">

        <ui:define name="titulo">
                <p:outputPanel>Login</p:outputPanel>
        </ui:define>

        <ui:define name="conteudo">
         
        
        <h:messages globalOnly="true" />
            
            <h:form id="login">
                <p:fieldset legend="Login">
                    <h:panelGrid columns="3">

                        <p:outputLabel value="Email:" for="email" />
                		<p:inputText id="email" value="#{loginMB.usuarioLogin.email}" required="true">
                    		<f:passThroughAttribute name="type" value="email" />
                		</p:inputText>
                		<p:message for="email" id="messageEmail" />

                		<p:outputLabel value="Senha:" for="senha" />		
                        <p:password id="senha" value="#{loginMB.usuarioLogin.senha}" feedback="true" required="true" />
                            
                        <h:message for="senha" id="messageSenha" />

                        <p:commandButton value="Efetue Login" action="#{loginMB.efetuaLogin}" update="@form" process="@form" />
                    </h:panelGrid>
            	</p:fieldset>    
            </h:form>
       </ui:define>
	</ui:composition>
</html>

src/main/webapp/usuarioLogin.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions">

<ui:composition template="_template.xhtml">

	<ui:define name="titulo">
		<p:outputPanel>Usuários adm</p:outputPanel>
	</ui:define>

	<ui:define name="conteudo">


		<h:messages globalOnly="true" />

		<h:form id="usuarioLogin">
			<p:fieldset legend="Dados do Usuário">
				<h:panelGrid columns="2">

					<p:outputLabel value="Email:" for="email" />
					<p:inputText id="email" value="#{usuarioLoginMB.usuarioLogin.email}"
						required="true">
						<f:validateLength minimum="1" />
					</p:inputText>

					<p:outputLabel value="Senha:" for="senha" />
					<p:password id="senha" value="#{usuarioLoginMB.usuarioLogin.senha}"	required="true" feedback="true">
						<f:validateLength minimum="1" />
					</p:password>

				</h:panelGrid>

				
				<p:commandButton value="Gravar" action="#{usuarioLoginMB.gravar}"
					process="@form" update="@form formTabelaUsuarios" ajax="false" />
			</p:fieldset>
		</h:form>

		<h:form id="formTabelaUsuarios">
			<p:dataTable var="usuarioLogin" value="#{usuarioLoginMB.usuarios}" rows="10"
				paginator="true">
				
				<f:facet name="header">
                    	Lista de Usuários Cadastrados
                </f:facet>
				
				<p:column headerText="Código" sortBy="#{usuarioLogin.id}"
					filterBy="#{usuarioLogin.id}">
					<h:outputText value="#{usuarioLogin.id}" />
				</p:column>
								
				<p:column headerText="Email" sortBy="#{usuarioLogin.email}"
					filterBy="#{usuarioLogin.email}">
					<h:outputText value="#{usuarioLogin.email}"/>
				</p:column>

				<!-- Alterar  -->
				<p:column headerText="Alterar">
					<p:commandButton icon="fa fa-fw fa-edit" value="Alterar"
						update=":usuarioLogin">
						<f:setPropertyActionListener value="#{usuarioLogin}"
							target="#{usuarioLoginMB.usuarioLogin}" />
					</p:commandButton>
				</p:column>

				<!-- Remover -->
				<p:column headerText="Remover">
					<p:commandButton icon="fa fa-fw fa-remove" value="Remover"
						action="#{usuarioLoginMB.delete(usuarioLogin)}" update="@form" />
				</p:column>
			</p:dataTable>
		</h:form>


	</ui:define>
</ui:composition>

</html>